# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gollm < Formula
  desc ""
  homepage "https://github.com/chavdim/gollm"
  version "0.1.5"

  on_macos do
    url "https://github.com/chavdim/gollm/releases/download/v0.1.5/gollm_0.1.5_darwin_all.tar.gz"
    sha256 "f90cf422cbda4cba75d25739cb39e874f21df73ac74724cb170a4a62a5163f30"

    def install
      bin.install "gollm"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chavdim/gollm/releases/download/v0.1.5/gollm_0.1.5_linux_arm64.tar.gz"
      sha256 "125195d2ed9ca1ed3cdb1b8c68131327170bba726ed0a672cc73417151c4c6bd"

      def install
        bin.install "gollm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chavdim/gollm/releases/download/v0.1.5/gollm_0.1.5_linux_amd64.tar.gz"
      sha256 "a94183cca8b7590d0f5efb4bec27afb083e9b57e580ef1261675e09570ff248d"

      def install
        bin.install "gollm"
      end
    end
  end
end
